{
 "title": "Nodes(细粒度指标项)",
 "description": "Nearly all default values exported by Prometheus node exporter graphed.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Host:",
    "query": "label_values(node_boot_time_seconds, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Basic CPU / Mem / Disk Gauge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"$instance\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "singlestat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$instance\"} * 100) / node_memory_MemTotal_bytes{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Used SWAP",
   "type": "singlestat",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$instance\"} - node_memory_SwapFree_bytes{instance=\"$instance\"}) / (node_memory_SwapTotal_bytes{instance=\"$instance\"} )) * 100"
    }
   ]
  },
  {
   "title": "Used Root FS",
   "type": "singlestat",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$instance\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$instance\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load1{instance=\"$instance\"}) / count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU System Load (5m avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load5{instance=\"$instance\"}) / count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu)) * 100"
    }
   ]
  },
  { "title": "Basic CPU / Mem / Disk Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "description": "Total RAM",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total SWAP",
   "type": "singlestat",
   "description": "Total SWAP",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total RootFS",
   "type": "singlestat",
   "description": "Total RootFS",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$instance\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "System Load (1m avg)",
   "type": "singlestat",
   "description": "System Load (1m avg)",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load1{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$instance\"} - node_boot_time_seconds{instance=\"$instance\"}"
    }
   ]
  },
  { "title": "Basic CPU / Mem Graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=\"$instance\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=\"$instance\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=\"$instance\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=\"$instance\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=\"$instance\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"$instance\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"} - node_memory_MemFree_bytes{instance=\"$instance\"} - (node_memory_Cached_bytes{instance=\"$instance\"} + node_memory_Buffers_bytes{instance=\"$instance\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$instance\"} + node_memory_Buffers_bytes{instance=\"$instance\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$instance\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$instance\"} - node_memory_SwapFree_bytes{instance=\"$instance\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  { "title": "Basic Net / Disk Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$instance\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"$instance\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "CPU Memory Net Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"system\",instance=\"$instance\"}[5m])) * 100",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='user',instance=\"$instance\"}[5m])) * 100",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='nice',instance=\"$instance\"}[5m])) * 100",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"$instance\"}[5m])) * 100",
     "legendFormat": "Idle - Waiting for something to happen"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='iowait',instance=\"$instance\"}[5m])) * 100",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='irq',instance=\"$instance\"}[5m])) * 100",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='softirq',instance=\"$instance\"}[5m])) * 100",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='steal',instance=\"$instance\"}[5m])) * 100",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='guest',instance=\"$instance\"}[5m])) * 100",
     "legendFormat": "Guest - Time spent running a virtual CPU for a guest operating system"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"} - node_memory_MemFree_bytes{instance=\"$instance\"} - node_memory_Buffers_bytes{instance=\"$instance\"} - node_memory_Cached_bytes{instance=\"$instance\"} - node_memory_Slab_bytes{instance=\"$instance\"} - node_memory_PageTables_bytes{instance=\"$instance\"} - node_memory_SwapCached_bytes{instance=\"$instance\"}",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables_bytes{instance=\"$instance\"}",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=\"$instance\"}",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab_bytes{instance=\"$instance\"}",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$instance\"}",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$instance\"}",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$instance\"}",
     "legendFormat": "Unused - Free memory unasigned"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$instance\"} - node_memory_SwapFree_bytes{instance=\"$instance\"})",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{instance=\"$instance\"}",
     "legendFormat": "Harware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$instance\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=\"$instance\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=\"$instance\",device=~\"[a-z]*[a-z]\"}[5m])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=\"$instance\",device=~\"[a-z]*[a-z]\"}[5m])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=\"$instance\",device=~\"[a-z]*[a-z]\"}[5m])",
     "legendFormat": "{{device}} - Successfully read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=\"$instance\",device=~\"[a-z]*[a-z]\"}[5m])",
     "legendFormat": "{{device}} - Successfully written bytes"
    }
   ]
  },
  {
   "title": "I/O Usage Times",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "ms", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=\"$instance\",device=~\"[a-z]*[a-z]\"} [5m])",
     "legendFormat": "{{device}} - Milliseconds spent doing I/Os"
    }
   ]
  },
  { "title": "Memory Detail Meminfo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Memory Active / Inactive",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Inactive_bytes{instance=\"$instance\"}",
     "legendFormat": "Inactive - Memory which has been less recently used. It is more eligible to be reclaimed for other purposes"
    },
    {
     "expr": "node_memory_Active_bytes{instance=\"$instance\"}",
     "legendFormat": "Active - Memory that has been used more recently and usually not reclaimed unless absolutely necessary"
    }
   ]
  },
  {
   "title": "Memory Commited",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Committed_AS_bytes{instance=\"$instance\"}",
     "legendFormat": "Committed_AS - Amount of memory presently allocated on the system"
    },
    {
     "expr": "node_memory_CommitLimit_bytes{instance=\"$instance\"}",
     "legendFormat": "CommitLimit - Amount of memory currently available to be allocated on the system"
    }
   ]
  },
  {
   "title": "Memory Active / Inactive Detail",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Inactive_file_bytes{instance=\"$instance\"}",
     "legendFormat": "Inactive_file - File-backed memory on inactive LRU list"
    },
    {
     "expr": "node_memory_Inactive_anon_bytes{instance=\"$instance\"}",
     "legendFormat": "Inactive_anon - Anonymous and swap cache on inactive LRU list, including tmpfs (shmem)"
    },
    {
     "expr": "node_memory_Active_file_bytes{instance=\"$instance\"}",
     "legendFormat": "Active_file - File-backed memory on active LRU list"
    },
    {
     "expr": "node_memory_Active_anon_bytes{instance=\"$instance\"}",
     "legendFormat": "Active_anon - Anonymous and swap cache on active least-recently-used (LRU) list, including tmpfs"
    }
   ]
  },
  {
   "title": "Memory Writeback and Dirty",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Writeback_bytes{instance=\"$instance\"}",
     "legendFormat": "Writeback - Memory which is actively being written back to disk"
    },
    {
     "expr": "node_memory_WritebackTmp_bytes{instance=\"$instance\"}",
     "legendFormat": "WritebackTmp - Memory used by FUSE for temporary writeback buffers"
    },
    {
     "expr": "node_memory_Dirty_bytes{instance=\"$instance\"}",
     "legendFormat": "Dirty - Memory which is waiting to get written back to the disk"
    }
   ]
  },
  {
   "title": "Memory Shared and Mapped",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Mapped_bytes{instance=\"$instance\"}",
     "legendFormat": "Mapped - Used memory in mapped pages files which have been mmaped, such as libraries"
    },
    {
     "expr": "node_memory_Shmem_bytes{instance=\"$instance\"}",
     "legendFormat": "Shmem - Used shared memory (shared between several processes, thus including RAM disks)"
    }
   ]
  },
  {
   "title": "Memory Slab",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_SUnreclaim_bytes{instance=\"$instance\"}",
     "legendFormat": "SUnreclaim - Part of Slab, that cannot be reclaimed on memory pressure"
    },
    {
     "expr": "node_memory_SReclaimable_bytes{instance=\"$instance\"}",
     "legendFormat": "SReclaimable - Part of Slab, that might be reclaimed, such as caches"
    }
   ]
  },
  {
   "title": "Memory Vmalloc",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_VmallocChunk_bytes{instance=\"$instance\"}",
     "legendFormat": "VmallocChunk - Largest contigious block of vmalloc area which is free"
    },
    {
     "expr": "node_memory_VmallocTotal_bytes{instance=\"$instance\"}",
     "legendFormat": "VmallocTotal - Total size of vmalloc memory area"
    },
    {
     "expr": "node_memory_VmallocUsed_bytes{instance=\"$instance\"}",
     "legendFormat": "VmallocUsed - Amount of vmalloc area which is used"
    }
   ]
  },
  {
   "title": "Memory Bounce",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 105 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Bounce_bytes{instance=\"$instance\"}",
     "legendFormat": "Bounce - Memory used for block device bounce buffers"
    }
   ]
  },
  {
   "title": "Memory Anonymous",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_AnonHugePages_bytes{instance=\"$instance\"}",
     "legendFormat": "AnonHugePages - Memory in anonymous huge pages"
    },
    {
     "expr": "node_memory_AnonPages_bytes{instance=\"$instance\"}",
     "legendFormat": "AnonPages - Memory in user pages not backed by files"
    }
   ]
  },
  {
   "title": "Memory Kernel",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 115 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_KernelStack_bytes{instance=\"$instance\"}",
     "legendFormat": "KernelStack - Kernel memory stack. This is not reclaimable"
    }
   ]
  },
  {
   "title": "Memory HugePages Counter",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 125 },
   "yaxes": [
    { "format": "short", "label": "Pages" }
   ],
   "targets": [
    {
     "expr": "node_memory_HugePages_Free{instance=\"$instance\"}",
     "legendFormat": "HugePages_Free - Huge pages in the pool that are not yet allocated"
    },
    {
     "expr": "node_memory_HugePages_Rsvd{instance=\"$instance\"}",
     "legendFormat": "HugePages_Rsvd - Huge pages for which a commitment to allocate from the pool has been made, but no allocation has yet been made"
    },
    {
     "expr": "node_memory_HugePages_Surp{instance=\"$instance\"}",
     "legendFormat": "HugePages_Surp - Huge pages in the pool above the value in /proc/sys/vm/nr_hugepages"
    }
   ]
  },
  {
   "title": "Memory HugePages Size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 125 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_HugePages_Total{instance=\"$instance\"}",
     "legendFormat": "HugePages - Total size of the pool of huge pages"
    },
    {
     "expr": "node_memory_Hugepagesize_bytes{instance=\"$instance\"}",
     "legendFormat": "Hugepagesize - Huge Page size"
    }
   ]
  },
  {
   "title": "Memory DirectMap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_DirectMap1G{instance=\"$instance\"}",
     "legendFormat": "DirectMap1G - Amount of pages mapped as this size"
    },
    {
     "expr": "node_memory_DirectMap2M_bytes{instance=\"$instance\"}",
     "legendFormat": "DirectMap2M - Amount of pages mapped as this size"
    },
    {
     "expr": "node_memory_DirectMap4k_bytes{instance=\"$instance\"}",
     "legendFormat": "DirectMap4K - Amount of pages mapped as this size"
    }
   ]
  },
  {
   "title": "Memory Unevictable and MLocked",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 135 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Unevictable_bytes{instance=\"$instance\"}",
     "legendFormat": "Unevictable - Amount of unevictable memory that can't be swapped out for a variety of reasons"
    },
    {
     "expr": "node_memory_Mlocked_bytes{instance=\"$instance\"}",
     "legendFormat": "MLocked - Size of pages locked to memory using the mlock() system call"
    }
   ]
  },
  {
   "title": "Memory NFS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 145 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_NFS_Unstable_bytes{instance=\"$instance\"}",
     "legendFormat": "NFS Unstable - Memory in NFS pages sent to the server, but not yet commited to the storage"
    }
   ]
  },
  { "title": "Memory Detail Vmstat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 155 } },
  {
   "title": "Memory Pages In / Out",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 156 },
   "yaxes": [
    { "format": "short", "label": "Pages out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_vmstat_pgpgin{instance=\"$instance\"}[5m])",
     "legendFormat": "Pagesin - Page in operations"
    },
    {
     "expr": "irate(node_vmstat_pgpgout{instance=\"$instance\"}[5m])",
     "legendFormat": "Pagesout - Page out operations"
    }
   ]
  },
  {
   "title": "Memory Pages Swap In / Out",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 156 },
   "yaxes": [
    { "format": "short", "label": "Pages out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_vmstat_pswpin{instance=\"$instance\"}[5m])",
     "legendFormat": "Pswpin - Pages swapped in"
    },
    {
     "expr": "irate(node_vmstat_pswpout{instance=\"$instance\"}[5m])",
     "legendFormat": "Pswpout - Pages swapped out"
    }
   ]
  },
  {
   "title": "Memory Page Faults",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 166 },
   "yaxes": [
    { "format": "short", "label": "Faults" }
   ],
   "targets": [
    {
     "expr": "irate(node_vmstat_pgfault{instance=\"$instance\"}[5m])",
     "legendFormat": "Pgfault - Page major and minor fault operations"
    },
    {
     "expr": "irate(node_vmstat_pgmajfault{instance=\"$instance\"}[5m])",
     "legendFormat": "Pgmajfault - Major page fault operations"
    },
    {
     "expr": "irate(node_vmstat_pgfault{instance=\"$instance\"}[5m]) - irate(node_vmstat_pgmajfault{instance=\"$instance\"}[5m])",
     "legendFormat": "Pgminfault - Minnor page fault operations"
    }
   ]
  },
  { "title": "System Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 176 } },
  {
   "title": "Context Switches / Interrupts",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 177 },
   "yaxes": [
    { "format": "short", "label": "Counter" }
   ],
   "targets": [
    {
     "expr": "irate(node_context_switches_total{instance=\"$instance\"}[5m])",
     "legendFormat": "Context switches"
    },
    {
     "expr": "irate(node_intr_total{instance=\"$instance\"}[5m])",
     "legendFormat": "Interrupts"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 177 },
   "yaxes": [
    { "format": "short", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"$instance\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{instance=\"$instance\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{instance=\"$instance\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Entropy",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 187 },
   "yaxes": [
    { "format": "short", "label": "Entropy" }
   ],
   "targets": [
    {
     "expr": "node_entropy_available_bits{instance=\"$instance\"}",
     "legendFormat": "Entropy available to random number generators"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 187 },
   "yaxes": [
    { "format": "short", "label": "Descriptors" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{instance=\"$instance\"}",
     "legendFormat": "Maximum open file descriptors"
    },
    {
     "expr": "process_open_fds{instance=\"$instance\"}",
     "legendFormat": "Open file descriptors"
    }
   ]
  },
  {
   "title": "Processes Forks",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 197 },
   "yaxes": [
    { "format": "short", "label": "Forks / sec" }
   ],
   "targets": [
    {
     "expr": "rate(node_forks_total{instance=\"$instance\"}[5m])",
     "legendFormat": "Processes forks second"
    }
   ]
  },
  {
   "title": "Processes State",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 197 },
   "yaxes": [
    { "format": "short", "label": "Processes" }
   ],
   "targets": [
    {
     "expr": "node_procs_blocked{instance=\"$instance\"}",
     "legendFormat": "Processes blocked waiting for I/O to complete"
    },
    {
     "expr": "node_procs_running{instance=\"$instance\"}",
     "legendFormat": "Processes in runnable state"
    }
   ]
  },
  {
   "title": "Time Syncronized Status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 207 },
   "yaxes": [
    { "format": "short", "label": "Counter" }
   ],
   "targets": [
    {
     "expr": "node_timex_sync_status{instance=\"$instance\"}",
     "legendFormat": "Is clock synchronized to a reliable server (1 = yes, 0 = no)"
    },
    {
     "expr": "node_timex_frequency_adjustment_ratio{instance=\"$instance\"}",
     "legendFormat": "Local clock frequency adjustment"
    }
   ]
  },
  {
   "title": "Processes Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 207 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"$instance\"}",
     "legendFormat": "Processes virtual memory size in bytes"
    },
    {
     "expr": "process_resident_memory_bytes{instance=\"$instance\"}",
     "legendFormat": "Processes resident memory size in bytes"
    }
   ]
  },
  {
   "title": "Hardware temperature monitor",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 217 },
   "yaxes": [
    { "format": "celsius", "label": "Temperature" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"$instance\"}",
     "legendFormat": "{{ chip }} {{ sensor }} temp"
    },
    {
     "expr": "node_hwmon_temp_crit_celsius{instance=\"$instance\"}",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    }
   ]
  },
  {
   "title": "Time Syncronized Drift",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 217 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds{instance=\"$instance\"}",
     "legendFormat": "Estimated error in seconds"
    },
    {
     "expr": "node_timex_offset_seconds{instance=\"$instance\"}",
     "legendFormat": "Time offset in between local system and reference clock"
    },
    {
     "expr": "node_timex_maxerror_seconds{instance=\"$instance\"}",
     "legendFormat": "Maximum error in seconds"
    }
   ]
  },
  {
   "title": "Disk Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 227 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk IOps Completed",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "iops", "label": "IO read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Reads completed"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Writes completed"
      }
     ]
    },
    {
     "title": "Disk R/W Data",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Read bytes"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Written bytes"
      }
     ]
    },
    {
     "title": "Disk R/W Time",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "ms", "label": "Millisec. read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_time_seconds_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Read time ms"
      },
      {
       "expr": "irate(node_disk_write_time_seconds_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Write time ms"
      }
     ]
    },
    {
     "title": "Disk IOs Weighted",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "ms", "label": "Milliseconds" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_time_weighted_seconds_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - IO time weighted"
      }
     ]
    },
    {
     "title": "Disk R/W Merged",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "iops", "label": "I/Os" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_merged_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Read merged"
      },
      {
       "expr": "irate(node_disk_writes_merged_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Write merged"
      }
     ]
    },
    {
     "title": "Milliseconds Spent Doing I/Os",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "ms", "label": "Milliseconds" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - IO time ms"
      }
     ]
    },
    {
     "title": "Disk IOs Current in Progress",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "iops", "label": "I/Os" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_now{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - IO now"
      }
     ]
    },
    {
     "title": "Open Error File",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "node_textfile_scrape_error{instance=\"$instance\"}",
       "legendFormat": "Textfile scrape error (1 = true)"
      }
     ]
    }
   ]
  },
  {
   "title": "Filesystem Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 228 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filesystem space available",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{instance=\"$instance\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}} - Available"
      }
     ]
    },
    {
     "title": "File Nodes Free",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "File Nodes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_files_free{instance=\"$instance\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}} - Free file nodes"
      }
     ]
    },
    {
     "title": "File Descriptor",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Files" }
     ],
     "targets": [
      {
       "expr": "node_filefd_maximum{instance=\"$instance\"}",
       "legendFormat": "Max open files"
      },
      {
       "expr": "node_filefd_allocated{instance=\"$instance\"}",
       "legendFormat": "Open files"
      }
     ]
    },
    {
     "title": "File Nodes Size",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "File Nodes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_files{instance=\"$instance\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}} - File nodes total"
      }
     ]
    },
    {
     "title": "Filesystem in ReadOnly",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Read Only" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_readonly{instance=\"$instance\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}} - ReadOnly"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 229 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic by Packets",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_packets_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "irate(node_network_transmit_packets_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    },
    {
     "title": "Network Traffic Errors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_errs_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Receive errors"
      },
      {
       "expr": "irate(node_network_transmit_errs_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Rransmit errors"
      }
     ]
    },
    {
     "title": "Network Traffic Drop",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_drop_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Receive drop"
      },
      {
       "expr": "irate(node_network_transmit_drop_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Transmit drop"
      }
     ]
    },
    {
     "title": "Network Traffic Compressed",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_compressed_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Receive compressed"
      },
      {
       "expr": "irate(node_network_transmit_compressed_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Transmit compressed"
      }
     ]
    },
    {
     "title": "Network Traffic Multicast",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_multicast_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Receive multicast"
      }
     ]
    },
    {
     "title": "Network Traffic Fifo",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_fifo_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Receive fifo"
      },
      {
       "expr": "irate(node_network_transmit_fifo_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Transmit fifo"
      }
     ]
    },
    {
     "title": "Network Traffic Frame",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_frame_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Receive frame"
      }
     ]
    },
    {
     "title": "Network Traffic Carrier",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_transmit_carrier_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Statistic transmit_carrier"
      }
     ]
    },
    {
     "title": "Network Traffic Colls",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_transmit_colls_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Transmit colls"
      }
     ]
    },
    {
     "title": "NF Contrack",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "short", "label": "Entries" }
     ],
     "targets": [
      {
       "expr": "node_nf_conntrack_entries{instance=\"$instance\"}",
       "legendFormat": "NF conntrack entries"
      },
      {
       "expr": "node_nf_conntrack_entries_limit{instance=\"$instance\"}",
       "legendFormat": "NF conntrack limit"
      }
     ]
    },
    {
     "title": "ARP Entries",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short", "label": "Entries" }
     ],
     "targets": [
      {
       "expr": "node_arp_entries{instance=\"$instance\"}",
       "legendFormat": "{{ device }} - ARP entries"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Sockstat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 230 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sockstat TCP",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "Sockets" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_TCP_alloc{instance=\"$instance\"}",
       "legendFormat": "TCP_alloc - Allocated sockets"
      },
      {
       "expr": "node_sockstat_TCP_inuse{instance=\"$instance\"}",
       "legendFormat": "TCP_inuse - Tcp sockets currently in use"
      },
      {
       "expr": "node_sockstat_TCP_mem{instance=\"$instance\"}",
       "legendFormat": "TCP_mem - Used memory for tcp"
      },
      {
       "expr": "node_sockstat_TCP_orphan{instance=\"$instance\"}",
       "legendFormat": "TCP_orphan - Orphan sockets"
      },
      {
       "expr": "node_sockstat_TCP_tw{instance=\"$instance\"}",
       "legendFormat": "TCP_tw - Sockets wating close"
      }
     ]
    },
    {
     "title": "Sockstat UDP",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "Sockets" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_UDPLITE_inuse{instance=\"$instance\"}",
       "legendFormat": "UDPLITE_inuse - Udplite sockets currently in use"
      },
      {
       "expr": "node_sockstat_UDP_inuse{instance=\"$instance\"}",
       "legendFormat": "UDP_inuse - Udp sockets currently in use"
      },
      {
       "expr": "node_sockstat_UDP_mem{instance=\"$instance\"}",
       "legendFormat": "UDP_mem - Used memory for udp"
      }
     ]
    },
    {
     "title": "Sockstat Used",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "Sockets" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_sockets_used{instance=\"$instance\"}",
       "legendFormat": "Sockets_used - Sockets currently in use"
      }
     ]
    },
    {
     "title": "Sockstat Memory Size",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_TCP_mem_bytes{instance=\"$instance\"}",
       "legendFormat": "TCP_mem_bytes - "
      },
      {
       "expr": "node_sockstat_UDP_mem_bytes{instance=\"$instance\"}",
       "legendFormat": "UDP_mem_bytes - "
      }
     ]
    },
    {
     "title": "Sockstat FRAG / RAW",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short", "label": "Sockets" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_FRAG_inuse{instance=\"$instance\"}",
       "legendFormat": "FRAG_inuse - Frag sockets currently in use"
      },
      {
       "expr": "node_sockstat_FRAG_memory{instance=\"$instance\"}",
       "legendFormat": "FRAG_memory - Used memory for frag"
      },
      {
       "expr": "node_sockstat_RAW_inuse{instance=\"$instance\"}",
       "legendFormat": "RAW_inuse - Raw sockets currently in use"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Netstat TCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 231 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP Segments",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Segments out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Tcp_InCsumErrors{instance=\"$instance\"}[5m])",
       "legendFormat": "InCsumErrors - Segments received with checksum errors"
      },
      {
       "expr": "irate(node_netstat_Tcp_InErrs{instance=\"$instance\"}[5m])",
       "legendFormat": "InErrs - Segments received in error (e.g., bad TCP checksums)"
      },
      {
       "expr": "irate(node_netstat_Tcp_InSegs{instance=\"$instance\"}[5m])",
       "legendFormat": "InSegs - Segments received, including those received in error. This count includes segments received on currently established connections"
      },
      {
       "expr": "irate(node_netstat_Tcp_OutRsts{instance=\"$instance\"}[5m])",
       "legendFormat": "OutRsts - Segments sent containing the RST flag"
      },
      {
       "expr": "irate(node_netstat_Tcp_OutSegs{instance=\"$instance\"}[5m])",
       "legendFormat": "OutSegs - Segments sent, including those on current connections but excluding those containing only retransmitted octets"
      },
      {
       "expr": "irate(node_netstat_Tcp_RetransSegs{instance=\"$instance\"}[5m])",
       "legendFormat": "RetransSegs - Segments retransmitted - that is, the number of TCP segments transmitted containing one or more previously transmitted octets"
      }
     ]
    },
    {
     "title": "TCP Connections",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{instance=\"$instance\"}",
       "legendFormat": "CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT"
      },
      {
       "expr": "node_netstat_Tcp_MaxConn{instance=\"$instance\"}",
       "legendFormat": "MaxConn - Limit on the total number of TCP connections the entity can support (Dinamic is \"-1\")"
      }
     ]
    },
    {
     "title": "TCP Retransmission",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "ms", "label": "Milliseconds" }
     ],
     "targets": [
      {
       "expr": "node_netstat_Tcp_RtoMax{instance=\"$instance\"}",
       "legendFormat": "RtoMax - Maximum value permitted by a TCP implementation for the retransmission timeout, measured in milliseconds"
      },
      {
       "expr": "node_netstat_Tcp_RtoMin{instance=\"$instance\"}",
       "legendFormat": "RtoMin - Minimum value permitted by a TCP implementation for the retransmission timeout, measured in milliseconds"
      }
     ]
    },
    {
     "title": "TCP Direct Transition",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=\"$instance\"}[5m])",
       "legendFormat": "ActiveOpens - TCP connections that have made a direct transition to the SYN-SENT state from the CLOSED state"
      },
      {
       "expr": "irate(node_netstat_Tcp_AttemptFails{instance=\"$instance\"}[5m])",
       "legendFormat": "AttemptFails - TCP connections that have made a direct transition to the CLOSED state from either the SYN-SENT and SYN-RCVD"
      },
      {
       "expr": "irate(node_netstat_Tcp_EstabResets{instance=\"$instance\"}[5m])",
       "legendFormat": "EstabResets - TCP connections that have made a direct transition to the CLOSED state from either the ESTABLISHED state or the CLOSE-WAIT state"
      },
      {
       "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=\"$instance\"}[5m])",
       "legendFormat": "PassiveOpens - TCP connections that have made a direct transition to the SYN-RCVD state from the LISTEN state"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Netstat UDP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 232 },
   "collapsed": true,
   "panels": [
    {
     "title": "UDP In / Out",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 86 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Udp_InDatagrams{instance=\"$instance\"}[5m])",
       "legendFormat": "InDatagrams - Datagrams received"
      },
      {
       "expr": "irate(node_netstat_Udp_OutDatagrams{instance=\"$instance\"}[5m])",
       "legendFormat": "OutDatagrams - Datagrams sent"
      }
     ]
    },
    {
     "title": "UDP Errors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 86 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Udp_InCsumErrors{instance=\"$instance\"}[5m])",
       "legendFormat": "InCsumErrors - Datagrams with checksum errors"
      },
      {
       "expr": "irate(node_netstat_Udp_InErrors{instance=\"$instance\"}[5m])",
       "legendFormat": "InErrors - Datagrams that could not be delivered to an application"
      },
      {
       "expr": "irate(node_netstat_Udp_RcvbufErrors{instance=\"$instance\"}[5m])",
       "legendFormat": "RcvbufErrors - Datagrams for which not enough socket buffer memory to receive"
      },
      {
       "expr": "irate(node_netstat_Udp_SndbufErrors{instance=\"$instance\"}[5m])",
       "legendFormat": "SndbufErrors - Datagrams for which not enough socket buffer memory to transmit"
      },
      {
       "expr": "irate(node_netstat_Udp_NoPorts{instance=\"$instance\"}[5m])",
       "legendFormat": "NoPorts - Datagrams received on a port with no listener"
      }
     ]
    },
    {
     "title": "UDP Lite In / Out",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 96 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_UdpLite_InDatagrams{instance=\"$instance\"}[5m])",
       "legendFormat": "InDatagrams - Packets received"
      },
      {
       "expr": "irate(node_netstat_UdpLite_OutDatagrams{instance=\"$instance\"}[5m])",
       "legendFormat": "OutDatagrams - Packets sent"
      }
     ]
    },
    {
     "title": "UDP Lite Errors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 96 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_UdpLite_InCsumErrors{instance=\"$instance\"}[5m])",
       "legendFormat": "InCsumErrors - Datagrams with checksum errors"
      },
      {
       "expr": "irate(node_netstat_UdpLite_InErrors{instance=\"$instance\"}[5m])",
       "legendFormat": "InErrors - Datagrams that could not be delivered to an application"
      },
      {
       "expr": "irate(node_netstat_UdpLite_RcvbufErrors{instance=\"$instance\"}[5m])",
       "legendFormat": "RcvbufErrors - Datagrams for which not enough socket buffer memory to receive"
      },
      {
       "expr": "irate(node_netstat_UdpLite_SndbufErrors{instance=\"$instance\"}[5m])",
       "legendFormat": "SndbufErrors - Datagrams for which not enough socket buffer memory to transmit"
      },
      {
       "expr": "irate(node_netstat_UdpLite_NoPorts{instance=\"$instance\"}[5m])",
       "legendFormat": "NoPorts - Datagrams received on a port with no listener"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 233 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Exporter Scrape Time",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "s", "label": "Seconds" }
     ],
     "targets": [
      {
       "expr": "node_scrape_collector_duration_seconds{instance=\"$instance\"}",
       "legendFormat": "{{collector}} - Scrape duration"
      }
     ]
    },
    {
     "title": "Node Exporter Scrape Success",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "node_scrape_collector_success{instance=\"$instance\"}",
       "legendFormat": "{{collector}} - Scrape success"
      }
     ]
    }
   ]
  }
 ]
}