{
 "title": "主机监控",
 "tags": [
  "hosts",
  "prometheus",
  "node-exporter"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node:",
    "query": "label_values(node_boot_time_seconds, instance)"
   },
   {
    "name": "job",
    "label": "Job:",
    "query": "label_values(node_boot_time_seconds, job)"
   },
   {
    "name": "port",
    "label": "Port:",
    "query": "label_values(node_boot_time_seconds{instance=~\"$node:(.*)\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "服务器运行时间",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$node:$port\",job=~\"$job\"} - node_boot_time_seconds{instance=~\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "CPU核心数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "总内存 (Size)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:.*\"}"
    }
   ]
  },
  {
   "title": "磁盘容量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 17, "y": 1 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{instance=~\"$node:$port\", device=~\"/dev/.*\"}) / count(node_filesystem_size_bytes{instance=~\"$node:$port\", device=~\"/dev/.*\"})"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ( node_memory_MemAvailable_bytes{instance=~\"$node:.*\"} / node_memory_MemTotal_bytes{instance=~\"$node:.*\"} * 100 )"
    }
   ]
  },
  {
   "title": "已使用内存 (Size)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:.*\"} - node_memory_MemAvailable_bytes{instance=~\"$node:.*\"}"
    }
   ]
  },
  {
   "title": "剩余可用内存 (Size)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$node:.*\"}"
    }
   ]
  },
  {
   "title": "SWAP (Size)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 17, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$node:.*\"}"
    }
   ]
  },
  { "title": "CPU信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU使用率",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node:$port\",job=~\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU负载(1m avg)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"$node:$port\",job=~\"$job\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU负载(5m avg)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load5{instance=~\"$node:$port\",job=~\"$job\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$node:$port\"}[1m])) * 100)",
     "legendFormat": "cpu-{{cpu}}"
    }
   ]
  },
  {
   "title": "负载",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_load1{instance=~\"$node:$port\"})",
     "legendFormat": "load1"
    },
    {
     "expr": "sum(node_load5{instance=~\"$node:$port\"})",
     "legendFormat": "load5"
    },
    {
     "expr": "sum(node_load15{instance=~\"$node:$port\"})",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "CPU分配",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{instance=~\"$node:$port\", mode!=\"idle\"}[5m])",
     "legendFormat": "cpu{{cpu}}-{{mode}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "已使用内存 (Size)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:.*\"} - node_memory_MemAvailable_bytes{instance=~\"$node:.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "已使用内存",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100-(node_memory_MemAvailable_bytes{instance=~\"$node:.*\"}  / node_memory_MemTotal_bytes{instance=~\"$node:.*\"}) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "内存分配 (Size)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:$port\"} - node_memory_MemFree_bytes{instance=~\"$node:$port\"} - node_memory_Cached_bytes{instance=~\"$node:$port\"} - node_memory_Buffers_bytes{instance=~\"$node:$port\"} - node_memory_Slab_bytes{instance=~\"$node:$port\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$node:$port\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node:$port\"} + node_memory_Slab_bytes{instance=~\"$node:$port\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node:$port\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "内存分配 ",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "( node_memory_MemTotal_bytes{instance=~\"$node:$port\"} - node_memory_MemFree_bytes{instance=~\"$node:$port\"} - node_memory_Cached_bytes{instance=~\"$node:$port\"} - node_memory_Buffers_bytes{instance=~\"$node:$port\"} - node_memory_Slab_bytes{instance=~\"$node:$port\"}) / node_memory_MemTotal_bytes{instance=~\"$node:$port\"} * 100",
     "legendFormat": "Used"
    },
    {
     "expr": "( node_memory_Buffers_bytes{instance=~\"$node:$port\"}) / node_memory_MemTotal_bytes{instance=~\"$node:$port\"} * 100",
     "legendFormat": "Buffers"
    },
    {
     "expr": "( node_memory_Cached_bytes{instance=~\"$node:$port\"} + node_memory_Slab_bytes{instance=~\"$node:$port\"}) / node_memory_MemTotal_bytes{instance=~\"$node:$port\"} * 100",
     "legendFormat": "Cached"
    },
    {
     "expr": "( node_memory_MemFree_bytes{instance=~\"$node:$port\"}) / node_memory_MemTotal_bytes{instance=~\"$node:$port\"} * 100",
     "legendFormat": "Free"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "接收流量总数",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 66 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{instance=~\"$node:$port\"}[24h]))"
    }
   ]
  },
  {
   "title": "发送流量总数",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 66 },
   "format": "bytes",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=~\"$node:$port\"}[24h]))"
    }
   ]
  },
  {
   "title": "网卡接收/发送流量",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$node:$port\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[5m]) > 0",
     "legendFormat": "{{device}}-transmit"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$node:$port\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[5m]) > 0",
     "legendFormat": "{{device}}-receive"
    }
   ]
  },
  {
   "title": "网卡接收/发送包",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_packets_total{instance=~\"$node:$port\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[5m]) > 0",
     "legendFormat": "{{device}}-transmit"
    },
    {
     "expr": "irate(node_network_receive_packets_total{instance=~\"$node:$port\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[5m]) > 0",
     "legendFormat": "{{device}}-receive"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "磁盘使用率 (%)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 83 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100-((sum(node_filesystem_avail_bytes{instance=~\"$node:$port\", device=~\"/dev/.*\"}) / count(node_filesystem_avail_bytes{instance=~\"$node:$port\", device=~\"/dev/.*\"})) / (sum(node_filesystem_size_bytes{instance=~\"$node:$port\", device=~\"/dev/.*\"}) / count(node_filesystem_size_bytes{instance=~\"$node:$port\", device=~\"/dev/.*\"}))) * 100"
    }
   ]
  },
  {
   "title": "磁盘使用空间",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 83 },
   "format": "gbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_filesystem_size_bytes{instance=~\"$node:$port\",job=~\"$job\",device=~\"/dev/.*\"} - node_filesystem_avail_bytes{instance=~\"$node:$port\",job=~\"$job\",device=~\"/dev/.*\"}) by (device)/1024/1024/1024",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "磁盘剩余空间",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 83 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes{instance=~\"$node:$port\", device=~\"/dev/.*\"}) / count(node_filesystem_avail_bytes{instance=~\"$node:$port\", device=~\"/dev/.*\"})"
    }
   ]
  },
  {
   "title": "磁盘读写",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{device=~\"[a-z]*[a-z]\",instance=~\"$node:$port\",job=~\"$job\"}[5m])",
     "legendFormat": "read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=~\"[a-z]*[a-z]\",instance=~\"$node:$port\",job=~\"$job\"}[5m])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "iops-读写",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{device=~\"[a-z]*[a-z]\",instance=~\"$node:$port\",job=~\"$job\"}[1m])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{device=~\"[a-z]*[a-z]\",instance=~\"$node:$port\",job=~\"$job\"}[1m])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Time-读写",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{device=\"sda\",instance=~\"$node:$port\",job=~\"$job\"}[5m])",
     "legendFormat": "read"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{device=\"sda\",instance=~\"$node:$port\",job=~\"$job\"}[5m])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "File Descriptor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "short", "label": "Files" }
   ],
   "targets": [
    {
     "expr": "node_filefd_maximum{instance=~\"$node:.*\"}",
     "legendFormat": "Max open files"
    },
    {
     "expr": "node_filefd_allocated{instance=~\"$node:.*\"}",
     "legendFormat": "Open files"
    }
   ]
  }
 ]
}