{
 "title": "容器监控",
 "description": "Docker swarm monitor with Prometheus, cAdvisor, Node Exporter and Grafana",
 "tags": [
  "prometheus",
  "cAdvisor",
  "node-exporter",
  "alertmanager"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "server",
    "label": "Node",
    "query": "label_values(node_boot_time_seconds, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "服务器运行时间",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"$server:.*\"}"
    }
   ]
  },
  {
   "title": "容器数量",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\".+\",instance=~\"$server:.*\"}[$interval]))"
    }
   ]
  },
  {
   "title": "磁盘使用率 (%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100-((sum(node_filesystem_avail_bytes{fstype=~\"xfs|ext4\",instance=~\"$server:.*\"}) / count(node_filesystem_avail_bytes{fstype=~\"xfs|ext4\",instance=~\"$server:.*\"})) / (sum(node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=~\"$server:.*\"}) / count(node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=~\"$server:.*\"}))) * 100"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (1 - avg(irate(node_cpu_seconds_total{mode='idle',instance=~\"$server:.*\"}[$interval])) by (instance,job))"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"$server:.*\"} - (node_memory_MemFree_bytes{instance=~\"$server:.*\"}+node_memory_Cached_bytes{instance=~\"$server:.*\"}+node_memory_Buffers_bytes{instance=~\"$server:.*\"}))/node_memory_MemTotal_bytes{instance=~\"$server:.*\"} * 100"
    }
   ]
  },
  {
   "title": "已使用内存 (Size)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$server:.*\"} - (node_memory_MemFree_bytes{instance=~\"$server:.*\"}+node_memory_Cached_bytes{instance=~\"$server:.*\"}+node_memory_Buffers_bytes{instance=~\"$server:.*\"})"
    }
   ]
  },
  {
   "title": "总内存(Size)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$server:.*\"}"
    }
   ]
  },
  {
   "title": "容器CPU使用率 (%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\",instance=~\"$server:.*\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "容器内存使用 (Size)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\".+\",instance=~\"$server:.*\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "容器网络接收速率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{image!=\"\",name=~\".+\",instance=~\"$server:.*\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "容器网络发送速率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{image!=\"\",name=~\".+\",instance=~\"$server:.*\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "容器文件系统写入速率(字节/秒)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{image!=\"\",name=~\".+\",instance=~\"$server:.*\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "容器文件系统读取速率(字节/秒)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{image!=\"\",name=~\".+\",instance=~\"$server:.*\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}