version: '2'
services:
    gitlab:
      image: 'gitlab/gitlab-ce:12.5.10-ce.0' #twang2218/gitlab-ce-zh:11.1.4
      container_name: 'gitlab'
      restart: always
      privileged: true
      hostname: '10.6.32.13'
      environment:
        TZ: 'Asia/Shanghai'
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://10.6.32.13:9000'
          gitlab_rails['time_zone'] = 'Asia/Shanghai'
          gitlab_rails['gitlab_shell_ssh_port'] = 9022
          nginx['listen_port'] = 9000
      ports:
        - '9000:9000'
        - '9022:22'
      volumes:
        - ./gitlab/config:/etc/gitlab
        - ./gitlab/data:/var/opt/gitlab
        - ./gitlab/logs:/var/log/gitlab