version: '3'

networks:
  monitor:
    driver: bridge

services:
  prometheus:
    image: registry.cyai.com/monitor/prometheus:v2.12.0
    container_name: prometheus
    hostname: prometheus
    restart: always
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=124d  #数据保存128天内的数据
    volumes:
      - /home/cyuser/monitor/:/etc/prometheus/
      - /home/cyuser/monitor-data/prometheus:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitor

  alertmanager:
    image: registry.cyai.com/monitor/alertmanager:v0.18.0
    container_name: alertmanager
    hostname: alertmanager
    restart: always
    volumes:
      - /home/cyuser/monitor/:/etc/alertmanager/
      - /home/cyuser/monitor-data/alertmanager:/alertmanager
    ports:
      - "9093:9093"
    networks:
      - monitor

  grafana:
    image: registry.cyai.com/monitor/grafana:6.3.5
    container_name: grafana
    hostname: grafana
    restart: always
    volumes:
      - /home/cyuser/monitor/grafana.ini:/etc/grafana/grafana.ini
      - /home/cyuser/monitor-data/grafana:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "80:3000"
    networks:
      - monitor

  node-exporter:
    image: registry.cyai.com/monitor/node-exporter:v0.18.0
    container_name: node-exporter
    hostname: node-exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      - monitor

  cadvisor:
    image: registry.cyai.com/monitor/cadvisor:v0.33.0
    container_name: cadvisor
    hostname: cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "9101:8080"
    networks:
      - monitor

  webhook:
    image: registry.cyai.com/monitor/cy-webhook:v1.0.3
    container_name: webhook
    hostname: webhook
    restart: always
    environment:
      - URLS=https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=445cc6b7-7957-48bb-8539-a017acb1ad51;https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=083d539e-3efa-4d3d-b54f-4675c0f0a01f
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - /etc/timezone:/etc/timezone
      - /home/cyuser/monitor/app.py:/usr/app.py
    ports:
      - "9102:5000"
    networks:
      - monitor
